version: 0.0
os: linux
files:
    - source: /
      destination: /var/www/PokeAPI
    - source: configuration/PokeAPI.service
      destination: /etc/systemd/system
hooks:
    ApplicationStop:
        - location: scripts/application-stop.sh
          runas: root
    BeforeInstall:
        - location: scripts/before-install.sh
          runas: root
    AfterInstall:
        - location: scripts/after-install.sh
          runas: root
        - location: scripts/install-aws-profile.sh
          runas: ubuntu
    ApplicationStart:
        - location: scripts/elb-v2/register_with_elb.sh
          timeout: 300
        - location: scripts/application-start.sh
          runas: root
    ValidateService:
        - location: scripts/validate-service.sh
          runas: root