version: 0.2
env:
    parameter-store:
        JWT_SECRET_TOKEN: pokeapi_jwt_secret_token
phases:
    install:
        runtime-versions:
            nodejs: 20
        commands:
            - npm install -g webpack webpack-cli
            - npm install --install-links=false
    build:
        commands:
            - echo "$environment"
            - npm run webpack
            - echo -e "PORT=3001" >> .env.production
            - echo -e "NODE_ENV=production" >> .env.production
            - echo -e "LOG_LEVEL=debug" >> .env.production
            - echo -e "JWT_SECRET_TOKEN=$JWT_SECRET_TOKEN" >> .env.production
artifacts:
    files:
        - "build/server.js"
        - "package.json"
        - "package-lock.json"
        - "configuration/PokeAPI.service"
        - "scripts/*"
        - ".env.production"